### ISSUE TITLE
add spot for user to upload negatives

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#39] opened 2024-09-05 15:26 UTC
This would allow the user to force some genes into the negative set that would have been otherwise positive

**Comment by vincerubinetti** [comment] 2024-09-17 16:58
Duplicate of #44

**Comment by ChristopherMancuso** [comment] 2024-09-17 17:13
this is not a duplicate of #44

**Comment by vincerubinetti** [comment] 2024-09-17 17:17
Duplicate of #43, typo

**Closed by vincerubinetti** 2024-09-17 17:17 UTC
Labels: enhancement
